version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_financemanager
    restart: always
    environment:
      POSTGRES_DB: financemanager
      POSTGRES_USER: gabrielboliveira
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
